### ISSUE TITLE
(Easy) Allow the user to give just the API URL in `init` function call

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-ios#4]
The `init` function call can be seen here: https://supertokens.io/docs/ios/init:
```
try SuperTokens.initialise(refreshTokenEndpoint: "https://api.example.com/session/refresh", sessionExpiryStatusCode: 401, refreshAPICustomHeaders: NSDictionary())
```

As seen above, the `refreshTokenEndpoint` must be a full path to their refresh API endpoint. Instead, we need to change it so that if they give:
- `https://api.example.com` or `https://api.example.com/`, it treats it as `https://api.example.com/session/refresh`
- `https://api.example.com/some/other/path`, it treats it as `https://api.example.com/some/other/path`

Essentially, we want them to just give them API domain for ease of use.

**Comment by nugmanoff** [comment]
Hey there! Can I help you on this one as part of Hacktoberfest 2020?

**Comment by rishabhpoddar** [comment]
Hey @nugmanoff 

Sure! I have assigned the issue to you, and please see the updated first comment for the details of this issue.

**Comment by rishabhpoddar** [comment]
Hey @nugmanoff , on second thought, the term `refreshTokenEndpoint` is not accurate anymore, since we are asking the users to give their API endpoint and not the whole path to that URL. So perhaps it should be changed to `apiEndpoint` in the`initialise` function signature?

**Comment by rishabhpoddar** [comment]
hey @nugmanoff , there is a small problem with this issue in terms of communication:

The user doesn't pass the refresh URL anymore, so the param cannot be called refreshTokenUrl, so we can rename it to apiEndpoint. But, in case they need to pass a custom refresh path, then they will be passing the whole URL, in which case, apiEndpoint is not a good name either.

One solution is to split this into two params: `apiEndpoint` and `refreshPath`, however, providing more params is annoying as well. 

Any thoughts please?

**Comment by nugmanoff** [comment]
hey @rishabhpoddar sorry for delayed response

I think you can move this details one level of abstraction higher by wrapping all of this branching logic into `enum` with two cases like `base` and `custom` (just some dummy names for example) and these cases will appropriate associated values that will represent different branching logic: whether user passed just an endpoint, or a full url, or just a relative path & etc

**Comment by rishabhpoddar** [comment]
@nugmanoff I see. However, what do you communicate to the user in the docs? That they need to pass the full URL or not? Or something like:

*This parameter should be equal to your API endpoint. In case you have a custom refresh API path (other than `/session/refresh`), please provide the full URL?*

Don't you think the above is unnecessarily complex?

**Comment by nugmanoff** [comment]
Complexity is never _unnecessary_ if it describes something complex. Moreover, if it is backed up by self-documenting, typed code (like `enum`) - it is more than ok
