### ISSUE TITLE
Headers case need to be lower case

### ISSUE THREAD

**Issue by mattanimation** [supertokens/supertokens-ios#49]
## Problem
`Utils.saveTokenFromHeaders` is failing to properly compare the constant values for the headers due to the headers from the server containing capital characters but all the constants are in lowercase.

how the constants look
![Screenshot 2023-09-07 at 11 20 41 PM](https://github.com/supertokens/supertokens-ios/assets/1426997/6a40743e-7b0b-4b69-a20e-dd9b252c7559)

how the headers are coming in (from a go back-end)
![Screenshot 2023-09-07 at 11 30 39 PM](https://github.com/supertokens/supertokens-ios/assets/1426997/1f6387de-f995-403c-985d-5e63b3415c27)

The thread ID for this topic on the discord: 1149591499567284304

## Proposed solution
- ensure the headers are lower-cased before the comparison is made

**Comment by nkshah2** [comment]
Hey @mattanimation 

Just checking up on progress on this and whether you need help with something

**Comment by nkshah2** [comment]
Hey @mattanimation 

This has been released with version 0.2.5, thanks for the contribution! Closing this, feel free to re-open if you face issues
