### ISSUE TITLE
(Easy) Change a successful refresh call to be when the status code is < 300 as opposed to == 200

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-ios#5]
In [this](https://github.com/supertokens/supertokens-ios/blob/master/SuperTokensSession/Classes/SuperTokensURLSession.swift#L129) function, we need to change `httpResponse.statusCode != 200` to `httpResponse.statusCode >= 300`

**Comment by nugmanoff** [comment]
Hey there! Can I help you on this one as part of Hacktoberfest 2020?
